


- name: kubeadm init Master nodes
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_init
  become: true

# - debug:
#     msg: "{{kubeadm_init.stdout | regex_search('(kubeadm join (?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:\\d{1,5}.+)') }}"

# - set_fact:
#     kubeadm_join: "{{kubeadm_init.stdout | regex_search('(kubeadm join (?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:\\d{1,5}.+)') }}"

###########################

- name: Verify if cluster definition exists
  stat: path="{{ inventory_dir }}/group_vars/{{ cluster_name }}/kubeadm.join.key.yml"
  delegate_to: localhost
  register: project_file


- name: Generate cluster folder
  file:  path={{ inventory_dir }}/group_vars/{{ cluster_name }} state=directory
  when: project_file.stat.exists == False
  delegate_to: localhost

- lineinfile:
    path: "{{ inventory_dir }}/group_vars/{{ cluster_name }}/kubeadm.join.key.yml"
    regexp: '^kubeadm_join:'
    line: "{{ item }}"
    create: yes
  delegate_to: localhost
  with_items:
    - "kubeadm_join: {{kubeadm_init.stdout | regex_search('(kubeadm join (?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:\\d{1,5}.+)') }}"

###########################

- name: create kubectl conf dir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
  with_items:
    - "{{ ansible_env.HOME }}/.kube"

- name: "Copy kubectl config file for user {{ ansible_env.USER }}"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0744
    remote_src: yes
  become: true

- name: Installing a pod network add-on - RBAC Auth
  shell: kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/rbac.yaml

- name: Installing a pod network add-on - Installing Canal Network
  shell: kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/canal.yaml
