- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    literal_line: |
      I am a literal line
    folded_line: >
      I am a folded line
    folded_strip_line: >-
      I am a folded stripped line

  tasks:
  - name: asd
    shell: bash -c "cat /home/rafael/Downloads/saida_kubeadm_init.out"
    register: out
    changed_when: false
    failed_when: out.rc > 0
    check_mode: no

  # - debug:
  #     msg: "{{item}}"
  #   with_items:
  #     - "{{out.stdout_lines | map('regex_findall','kubeadm') | map('join') | list }}"


  - debug:
      msg: "{{out.stdout | regex_search('(kubeadm join (?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:\\d{1,5}.+)') }}"
  # 
  # - debug:
  #     msg: "{{ item }}"
  #   with_items:
  #     - "{{out.stdout | regex_search('(kubeadm join (?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:\\d{1,5}.+)') }}"

  # - debug:
  #     msg: "{{ item }}"
  #   with_items:
  #     - "{{out.stdout_lines | map('regex_findall','kubeadm join (?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:\\d{1,5}.+') | list }}"

  # - debug:
  #     msg: "{{out.stdout_lines | map('regex_findall','kubeadm join [0-9]{3}') | map('join') | list }}"

  # - debug:
  #     msg: "{{out.stdout_lines[-1]}}"
